use std::{
    collections::{BTreeMap, HashMap},
    path::Path,
    time::{Duration, Instant},
};

use base64::{engine::general_purpose, Engine as _};
use dotenv::dotenv;
use reqwest::header;
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use tokio::sync::Mutex;

use crate::{api::DEFAULT_BASE_URL, errors::GemError, utils::get_mime_type};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ToolCode {
    pub shell: Shell,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GoogleSearchRetrieval {}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Tool {
    #[serde(rename = "google_search")]
    pub google_search_retrieval: GoogleSearchRetrieval,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Shell {
    pub code: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged, rename_all = "camelCase")]
pub enum PartData {
    InlineData {
        #[serde(rename = "inlineData")]
        inline_data: Blob,
    },
    FileData {
        #[serde(rename = "fileData")]
        file_data: FileData,
    },
    Text {
        text: String,
    },
    ToolCode {
        #[serde(rename = "toolCode")]
        tool_code: ToolCode,
    },
    FunctionCall {
        #[serde(rename = "functionCall")]
        function_call: FunctionCall,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FunctionCall {
    pub name: String,
    pub args: HashMap<String, Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
#[serde(rename_all = "lowercase")]
pub enum Role {
    Model,
    #[default]
    User,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")] // Ensure enum variants match the JSON casing
pub(crate) enum FinishReason {
    FinishReasonUnspecified, // Default value. This value is unused.
    Stop,                    // Natural stop point of the model or provided stop sequence.
    MaxTokens,  // The maximum number of tokens as specified in the request was reached.
    Safety,     // The response candidate content was flagged for safety reasons.
    Recitation, // The response candidate content was flagged for recitation reasons.
    Language,   // The response candidate content was flagged for using an unsupported language.
    Other,      // Unknown reason.
    Blocklist,  // Token generation stopped because the content contains forbidden terms.
    ProhibitedContent, // Token generation stopped for potentially containing prohibited content.
    Spii, // Token generation stopped because the content potentially contains Sensitive Personally Identifiable Information (SPII).
    MalformedFunctionCall, // The function call generated by the model is invalid.
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GenerateContentResponse {
    candidates: Vec<Candidate>,
    prompt_feedback: Option<PromptFeedback>,
    usage_metadata: Option<UsageMetadata>,
    model_version: Option<String>,
    response_id: Option<String>,
}

impl GenerateContentResponse {
    pub fn get_candidates(&self) -> &Vec<Candidate> {
        &self.candidates
    }

    pub fn get_results(&self) -> Vec<String> {
        let mut texts = Vec::new();
        for candidate in &self.candidates {
            if let Some(content) = candidate.get_content() {
                if let Some(text) = content.get_text() {
                    texts.push(text.clone());
                }
            }
        }
        texts
    }

    pub fn get_usage_metadata(&self) -> Option<&UsageMetadata> {
        self.usage_metadata.as_ref()
    }

    pub fn any_candidate_max_tokens(&self) -> bool {
        self.candidates
            .iter()
            .any(|candidate| candidate.finish_reason_code() == Some("MAX_TOKENS"))
    }

    pub(crate) fn feedback(&self) -> Option<BlockReason> {
        match self.prompt_feedback.is_some()
            && self
                .prompt_feedback
                .as_ref()
                .unwrap()
                .block_reason
                .is_some()
        {
            true => self.prompt_feedback.as_ref().unwrap().block_reason.clone(),
            false => None,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Candidate {
    content: Option<Content>,            // The content generated by the model
    finish_reason: Option<FinishReason>, // Enum to represent why the model stopped
    safety_ratings: Option<Vec<SafetyRating>>, // List of safety ratings for the response
    token_count: Option<i32>,            // The token count for this candidate
    index: Option<i32>,                  // Index of the candidate in the list
    #[serde(default)]
    pub function_call: Option<FunctionCall>,
}

impl Candidate {
    pub fn get_content(&self) -> Option<&Content> {
        self.content.as_ref()
    }

    pub(crate) fn is_blocked(&self) -> bool {
        (self.finish_reason == Some(FinishReason::Safety))
            || (self.finish_reason == Some(FinishReason::Recitation))
            || (self.finish_reason == Some(FinishReason::ProhibitedContent))
    }

    pub(crate) fn get_token_count(&self) -> Option<i32> {
        self.token_count
    }

    pub fn finish_reason_code(&self) -> Option<&'static str> {
        match self.finish_reason {
            Some(FinishReason::FinishReasonUnspecified) => Some("FINISH_REASON_UNSPECIFIED"),
            Some(FinishReason::Stop) => Some("STOP"),
            Some(FinishReason::MaxTokens) => Some("MAX_TOKENS"),
            Some(FinishReason::Safety) => Some("SAFETY"),
            Some(FinishReason::Recitation) => Some("RECITATION"),
            Some(FinishReason::Language) => Some("LANGUAGE"),
            Some(FinishReason::Other) => Some("OTHER"),
            Some(FinishReason::Blocklist) => Some("BLOCKLIST"),
            Some(FinishReason::ProhibitedContent) => Some("PROHIBITED_CONTENT"),
            Some(FinishReason::Spii) => Some("SPII"),
            Some(FinishReason::MalformedFunctionCall) => Some("MALFORMED_FUNCTION_CALL"),
            None => None,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Content {
    pub parts: Vec<Part>, // A vector of Part objects
    role: Option<Role>,   // Role field, optional; either 'user' or 'model'
}

impl Content {
    pub fn get_text(&self) -> Option<String> {
        for part in &self.parts {
            match &part.data {
                PartData::Text { text } => return Some(text.clone()),
                _ => continue,
            }
        }
        None
    }

    pub fn get_parts(&self) -> &Vec<Part> {
        &self.parts
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NoRoleContent {
    parts: Vec<Part>, // A vector of Part objects
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Part {
    #[serde(flatten)] // This enables the union-like behavior for the different possible types
    pub data: PartData, // Union field that can be one of several types
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Blob {
    pub mime_type: String,
    pub data: String,
}

impl Blob {
    pub fn new(mime_type: &str, data: &[u8]) -> Self {
        Blob {
            mime_type: mime_type.to_string(),
            data: general_purpose::STANDARD.encode(&data),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileData {
    pub mime_type: String,
    pub file_uri: String, // File URI
    #[serde(skip)]
    pub file_name: Option<String>,
}

impl FileData {
    pub fn file_name(&self) -> Option<&str> {
        self.file_name.as_deref()
    }

    pub fn infer_file_name_from_uri(&self) -> Option<String> {
        self.file_uri
            .split('/')
            .find(|segment| segment.starts_with("files/"))
            .map(ToOwned::to_owned)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct PromptFeedback {
    block_reason: Option<BlockReason>, // Block reason, optional
    safety_ratings: Vec<SafetyRating>, // A vector of SafetyRating objects
}

impl PromptFeedback {
    pub(crate) fn get_block_reason(&self) -> Option<BlockReason> {
        self.block_reason.clone()
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")] // Ensure enum variants match the JSON casing
pub(crate) enum BlockReason {
    BlockReasonUnspecified, // Default value, unused
    Safety,                 // Blocked for safety reasons
    Other,                  // Blocked for unknown reasons
    Blocklist,              // Blocked due to blacklist terms
    ProhibitedContent,      // Blocked due to prohibited content
}

impl std::fmt::Display for BlockReason {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            BlockReason::BlockReasonUnspecified => write!(f, "Unspecified"),
            BlockReason::Safety => write!(f, "Safety"),
            BlockReason::Other => write!(f, "Other"),
            BlockReason::Blocklist => write!(f, "Blocklist"),
            BlockReason::ProhibitedContent => write!(f, "Prohibited Content"),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct SafetyRating {
    category: Option<String>,    // The safety category
    probability: Option<String>, // The probability of the content being unsafe
    blocked: Option<bool>,       // Whether the content is blocked
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TokenDetails {
    modality: String,
    token_count: Option<i32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UsageMetadata {
    prompt_token_count: Option<i32>,     // Number of tokens in the prompt
    candidates_token_count: Option<i32>, // Number of tokens in the generated candidates
    total_token_count: Option<i32>,      // Total number of tokens (prompt + candidates)
    cached_content_token_count: Option<i32>, // Number of tokens in cached content
    // candidates_token_count: Option<i32>, // Number of tokens in the generated candidates
    thoughts_token_count: Option<i32>, // Number of tokens in the generated thoughts
    prompt_token_details: Option<Vec<TokenDetails>>,
    candidate_tokens_details: Option<Vec<TokenDetails>>,
}

impl UsageMetadata {
    pub fn get_prompt_token_count(&self) -> Option<i32> {
        self.prompt_token_count
    }

    pub fn get_cached_content_token_count(&self) -> Option<i32> {
        self.cached_content_token_count
    }

    pub fn get_candidates_token_count(&self) -> Option<i32> {
        self.candidates_token_count
    }

    pub fn get_total_token_count(&self) -> Option<i32> {
        self.total_token_count
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct Status {
    code: i32,
    message: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct VideoMetadata {
    video_duration: String,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct File {
    name: String,
    uri: String,
    display_name: String,
    mime_type: String,
    size_bytes: String,
    create_time: String,
    update_time: String,
    expiration_time: String,
    sha256_hash: String,
    state: String,
    error: Option<Status>,
    video_metadata: Option<VideoMetadata>,
    #[serde(skip)]
    api_key: String,
}

impl File {
    pub(crate) async fn new(
        file_name: &str,
        bytes: Vec<u8>,
        mime_type: &str,
        api_key: &str,
        timeout: Option<Duration>,
        base_url: &str,
    ) -> Result<Self, GemError> {
        Self::upload(file_name, bytes, mime_type, api_key, timeout, base_url).await
    }

    async fn upload(
        file_name: &str,
        buffer: Vec<u8>,
        mime_type: &str,
        api_key: &str,
        timeout: Option<Duration>,
        base_url: &str,
    ) -> Result<Self, GemError> {
        let num_bytes = buffer.len();

        let mut client_builder = reqwest::Client::builder();
        if let Some(t) = timeout {
            client_builder = client_builder.timeout(t);
        } else {
            client_builder = client_builder.timeout(Duration::from_secs(300));
        }
        let client = client_builder.build().unwrap_or(reqwest::Client::new());

        let upload_url = format!("{}/upload/v1beta/files", base_url);

        let reserve_response = match client
            .post(upload_url)
            .query(&[("key", api_key)])
            .header("X-Goog-Upload-Protocol", "resumable")
            .header("X-Goog-Upload-Command", "start")
            .header("X-Goog-Upload-Header-Content-Length", num_bytes.to_string())
            .header("X-Goog-Upload-Header-Content-Type", mime_type)
            .header(header::CONTENT_TYPE, "application/json")
            .json(&json!({
                "file": { "display_name": file_name }
            }))
            .send()
            .await
        {
            Ok(response) => response,
            Err(e) => return Err(GemError::FileError(e.to_string())),
        };

        if !reserve_response.status().is_success() {
            let error_text = reserve_response.text().await.unwrap_or_default();
            return Err(GemError::FileError(format!(
                "Failed to start upload: {}",
                error_text
            )));
        }

        let location = match reserve_response.headers().get("X-Goog-Upload-URL") {
            Some(loc) => match loc.to_str() {
                Ok(l) => l,
                Err(e) => return Err(GemError::FileError(e.to_string())),
            },
            None => {
                return Err(GemError::FileError(
                    "X-Goog-Upload-URL header not found".to_string(),
                ))
            }
        };

        let upload_response = match client
            .put(location)
            .header("Content-Length", num_bytes.to_string())
            .header("X-Goog-Upload-Offset", "0")
            .header("X-Goog-Upload-Command", "upload, finalize")
            .body(buffer)
            .send()
            .await
        {
            Ok(response) => response,
            Err(e) => return Err(GemError::FileError(e.to_string())),
        };

        if !upload_response.status().is_success() {
            let error_text = upload_response.text().await.unwrap_or_default();
            return Err(GemError::FileError(format!(
                "Failed to upload bytes: {}",
                error_text
            )));
        }

        let upload_text_response = match upload_response.text().await {
            Ok(t) => t,
            Err(e) => return Err(GemError::FileError(e.to_string())),
        };

        let mut file: File = match serde_json::from_str::<Value>(&upload_text_response) {
            Ok(data) => match data.get("file") {
                Some(f) => match serde_json::from_value(f.clone()) {
                    Ok(file) => file,
                    Err(e) => {
                        log::error!("File error [0]: {} - Response: {}", e, upload_text_response);
                        return Err(GemError::FileError(e.to_string()));
                    }
                },
                None => {
                    return Err(GemError::FileError(
                        "File data not found in response".to_string(),
                    ))
                }
            },
            Err(e) => {
                log::error!("File error [1]: {} - Response: {}", e, upload_text_response);
                return Err(GemError::FileError(e.to_string()));
            }
        };

        let start_time = Instant::now();
        let time_limit = timeout.unwrap_or(Duration::from_secs(600));
        loop {
            if start_time.elapsed() > time_limit {
                return Err(GemError::FileError(format!(
                    "File processing timeout after {:?}",
                    time_limit
                )));
            }

            let file_state_response = match client
                .get(&format!("{}/v1beta/{}", base_url, file.name))
                .query(&[("key", api_key)])
                .send()
                .await
            {
                Ok(response) => response,
                Err(e) => return Err(GemError::FileError(e.to_string())),
            };

            let file_state_text = match file_state_response.text().await {
                Ok(t) => t,
                Err(e) => return Err(GemError::FileError(e.to_string())),
            };

            let file_state: File = match serde_json::from_str::<File>(&file_state_text) {
                Ok(f) => f,
                Err(e) => {
                    log::error!("File error [3]: {:#?}, response: {:#?}", e, file_state_text);
                    return Err(GemError::FileError(
                        "Failed to parse file state".to_string(),
                    ));
                }
            };

            if file_state.state == "ACTIVE" {
                break;
            } else if file_state.state == "FAILED" {
                return Err(GemError::FileError(
                    file_state
                        .error
                        .clone()
                        .unwrap_or(Status {
                            code: 0,
                            message: "File processing failed".to_string(),
                        })
                        .message,
                ));
            } else if file_state.state != "PROCESSING" {
                log::warn!("Unknown file state: {}", file_state.state);
                return Err(GemError::FileError(format!(
                    "File processing unknown state: {}",
                    file_state.state
                )));
            }

            tokio::time::sleep(Duration::from_secs(3)).await;
        }

        file.api_key = api_key.to_string();
        Ok(file)
    }

    async fn delete(self) -> Result<(), GemError> {
        log::info!("Deleting file: {:#?}", self);
        if self.api_key == "" {
            log::info!("API key not found: {:#?}", self.display_name);
            return Err(GemError::FileError("API key not found".to_string()));
        }
        let client = reqwest::Client::new();
        match client
            .delete(self.uri)
            .query(&[("key", self.api_key.clone())])
            .send()
            .await
        {
            Ok(_) => {
                log::info!("File deleted successfully: {:#?}", self.display_name);
                Ok(())
            }
            Err(e) => Err(GemError::FileError(e.to_string())),
        }
    }
}

#[derive(Debug)]
pub struct FileManager {
    files: Mutex<HashMap<String, File>>,
    api_key: String,
    base_url: String,
}

impl FileManager {
    pub fn new() -> Self {
        dotenv().ok();
        let api_key = std::env::var("GEMINI_API_KEY").expect("Failed to load Gemini API key");

        Self {
            files: Mutex::new(HashMap::new()),
            api_key: api_key.to_string(),
            base_url: DEFAULT_BASE_URL.to_string(),
        }
    }

    pub fn set_base_url(&mut self, url: &str) {
        self.base_url = url.trim_end_matches('/').to_string();
    }

    pub async fn download_file_bytes(&self, file_name: &str) -> Result<Vec<u8>, GemError> {
        let normalized = if file_name.starts_with("files/") {
            file_name.to_string()
        } else {
            format!("files/{}", file_name.trim_start_matches('/'))
        };

        let url = format!("{}/v1beta/{}:download", self.base_url, normalized);
        let client = reqwest::Client::new();
        let response = client
            .get(url)
            .query(&[("key", self.api_key.clone()), ("alt", "media".to_string())])
            .send()
            .await
            .map_err(|err| GemError::FileError(err.to_string()))?;

        if !response.status().is_success() {
            let body = response.text().await.unwrap_or_default();
            return Err(GemError::FileError(format!(
                "Failed to download file content: {}",
                body
            )));
        }

        response
            .bytes()
            .await
            .map(|bytes| bytes.to_vec())
            .map_err(|err| GemError::FileError(err.to_string()))
    }

    pub async fn download_file_string(&self, file_name: &str) -> Result<String, GemError> {
        let bytes = self.download_file_bytes(file_name).await?;
        String::from_utf8(bytes).map_err(|err| GemError::FileError(err.to_string()))
    }

    pub async fn add_file_from_bytes(
        &self,
        file_name: &str,
        bytes: Vec<u8>,
        mime_type: &str,
        timeout: Option<Duration>,
    ) -> Result<FileData, GemError> {
        let hash = sha256::digest(&bytes);
        match self.get_file(&hash).await {
            Some(file) => Ok(file),
            None => {
                let file = File::new(
                    file_name,
                    bytes,
                    mime_type,
                    &self.api_key,
                    timeout,
                    &self.base_url,
                )
                .await?;
                let mime_type = file.mime_type.clone();
                let file_uri = file.uri.clone();
                let uploaded_name = file.name.clone();
                let mut files = self.files.lock().await;
                files.insert(hash, file);
                Ok(FileData {
                    mime_type,
                    file_uri,
                    file_name: Some(uploaded_name),
                })
            }
        }
    }

    pub async fn add_file(
        &mut self,
        file_path: &Path,
        timeout: Option<Duration>,
    ) -> Result<FileData, GemError> {
        if !file_path.exists() {
            return Err(GemError::FileError("File does not exist".to_string()));
        }

        let file_name = match file_path.file_name() {
            Some(name) if name.to_str().is_some() => name.to_str().unwrap(),
            _ => return Err(GemError::FileError("Invalid file name".to_string())),
        };

        let mut file = match std::fs::File::open(file_path) {
            Ok(f) => f,
            Err(e) => return Err(GemError::FileError(e.to_string())),
        };

        let mut buffer = Vec::new();
        match std::io::Read::read_to_end(&mut file, &mut buffer) {
            Ok(_) => (),
            Err(e) => return Err(GemError::FileError(e.to_string())),
        };

        let mime_type = match get_mime_type(file_path) {
            Some(ext) => ext,
            None => return Err(GemError::FileError("Unsupported file type".to_string())),
        };

        let hash = sha256::digest(&buffer);

        match self.get_file(&hash).await {
            Some(file) => Ok(file),
            None => {
                let file = File::new(
                    file_name,
                    buffer,
                    &mime_type,
                    &self.api_key,
                    timeout,
                    &self.base_url,
                )
                .await?;
                let mime_type = file.mime_type.clone();
                let file_uri = file.uri.clone();
                let uploaded_name = file.name.clone();
                let mut files = self.files.lock().await;
                files.insert(hash, file);
                Ok(FileData {
                    mime_type,
                    file_uri,
                    file_name: Some(uploaded_name),
                })
            }
        }
    }

    pub async fn check_file(&self, hash: &str) -> bool {
        let files = self.files.lock().await;
        for file in files.iter() {
            if file.0 == hash {
                return true;
            }
        }
        false
    }

    pub async fn get_file(&self, hash: &str) -> Option<FileData> {
        let mut to_remove = Vec::new();
        let mut files = self.files.lock().await;
        for file in files.iter() {
            match file.0 == hash {
                true if file.1.expiration_time
                    > (chrono::Utc::now() + chrono::Duration::minutes(10)).to_rfc3339() =>
                {
                    log::info!("Found cached File: {:#?}", file.1);
                    return Some(FileData {
                        mime_type: file.1.mime_type.clone(),
                        file_uri: file.1.uri.clone(),
                        file_name: Some(file.1.name.clone()),
                    });
                }
                true => {
                    to_remove.push(file.0.clone());
                }
                false => continue,
            }
        }

        for hash in to_remove {
            let file = files.remove(&hash);
            if let Some(file) = file {
                let _ = file.delete().await;
            }
        }

        None
    }

    pub async fn fetch_list(&mut self) -> Result<HashMap<String, File>, GemError> {
        let client = reqwest::Client::new();
        let mut files = Vec::new();
        let mut page_token: Option<String> = None;

        loop {
            let mut request = client.get(format!("{}/v1beta/files", self.base_url));

            if let Some(token) = &page_token {
                request = request.query(&[("pageToken", token), ("key", &self.api_key)]);
            } else {
                request = request.query(&[("key", &self.api_key)]);
            }

            let response = match request.send().await {
                Ok(response) => response,
                Err(e) => return Err(GemError::FileError(e.to_string())),
            };

            let response_text = match response.text().await {
                Ok(data) => data,
                Err(e) => return Err(GemError::FileError(e.to_string())),
            };

            let response_json: Value = match serde_json::from_str(&response_text) {
                Ok(data) => data,
                Err(e) => {
                    log::error!("File error [6]: {}, response: {}", e, response_text);
                    return Err(GemError::FileError(e.to_string()));
                }
            };

            match response_json.get("files") {
                Some(f) => match serde_json::from_value::<Vec<File>>(f.clone()) {
                    Ok(mut new_files) => files.append(&mut new_files),
                    Err(e) => {
                        log::error!("File error [7]: {}, response: {}", e, response_text);
                        return Err(GemError::FileError(e.to_string()));
                    }
                },
                None => {
                    break;
                }
            };

            page_token = response_json
                .get("nextPageToken")
                .and_then(|t| t.as_str().map(String::from));
            if page_token.is_none() {
                break;
            }
        }

        let mut files_map = self.files.lock().await;
        let mut files_map_clone = HashMap::new();
        for file in files_map.iter() {
            files_map_clone.insert(file.0.clone(), file.1.clone());
        }

        for mut file in files {
            file.api_key = self.api_key.clone();
            log::info!("File: {:#?}", file);
            files_map.insert(file.sha256_hash.clone(), file.clone());
            files_map_clone.insert(file.sha256_hash.clone(), file);
        }

        Ok(files_map_clone)
    }

    pub async fn delete_file(&mut self, hash: &str) -> Result<(), GemError> {
        let mut files = self.files.lock().await;
        let file = files.remove(hash);
        match file {
            Some(file) => file.delete().await,
            None => Ok(()),
        }
    }

    pub async fn clear_files(&mut self) {
        let mut files = self.files.lock().await;
        let keys: Vec<String> = files.keys().cloned().collect();
        for key in keys {
            if let Some(file) = files.remove(&key) {
                let _ = file.delete().await;
            }
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SafetySetting {
    category: HarmCategory,        // Enum for the harm category
    threshold: HarmBlockThreshold, // Enum for the harm block threshold
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")] // To match the JSON format
enum HarmCategory {
    HarmCategoryHateSpeech,
    HarmCategorySexuallyExplicit,
    HarmCategoryDangerousContent,
    HarmCategoryHarassment,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ErrorWrapper {
    pub error: Error,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Error {
    pub code: u32,
    pub message: String,
    pub status: String,
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Error {}: {} ({})", self.code, self.message, self.status)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")] // To match the JSON format
pub enum HarmBlockThreshold {
    HarmBlockThresholdUnspecified, // Unspecified threshold
    BlockLowAndAbove,              // Block content with NEGIGIBLE and above
    BlockMediumAndAbove,           // Block content with NEGIGIBLE, LOW, and above
    BlockOnlyHigh,                 // Block content with only HIGH harm probability
    BlockNone,                     // All content will be allowed
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
/// Create a new ThinkingConfig with a given thinking budget.
/// If not used, the model will decide whether to think or not.
/// Best to not use this, and let the model decide.
struct ThinkingConfig {
    thinking_budget: Option<u32>,
    //enable_thinking: bool,
}

impl ThinkingConfig {
    /// Create a new ThinkingConfig with a given thinking budget.
    /// If not used, the model will decide whether to think or not.
    /// Best to not use this, and let the model decide.
    pub(crate) fn new(thinking_budget: u32) -> Self {
        ThinkingConfig {
            thinking_budget: Some(thinking_budget),
            //thinking_enable: true,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct GenerationConfig {
    stop_sequences: Option<Vec<String>>, // Optional: Up to 5 stop sequences
    response_mime_type: Option<String>, // Optional: MIME type of the response (e.g., text/plain, application/json)
    max_output_tokens: Option<u32>,     // Optional: Max tokens for the response up to 8192
    temperature: Option<f32>,           // Optional: Controls randomness of the output [0.0, 2.0]
    top_p: Option<f32>, // Optional: Maximum cumulative probability for nucleus sampling
    top_k: Option<u32>, // Optional: Maximum number of tokens to consider for top-k sampling
    thinking_config: Option<ThinkingConfig>,
}

pub struct Settings {
    safety_settings: Option<Vec<SafetySetting>>,
    generation_config: Option<GenerationConfig>,
    system_instruction: Option<String>,
    stream_max_json_size: Option<u32>,
    enable_grounding_search: bool,
}

impl Settings {
    pub fn new() -> Self {
        Settings {
            safety_settings: None,
            generation_config: None,
            system_instruction: None,
            stream_max_json_size: Some(16384),
            enable_grounding_search: false,
        }
    }

    pub fn set_stream_max_json_size(&mut self, size: u32) {
        self.stream_max_json_size = Some(size);
    }

    pub fn set_all_safety_settings(&mut self, threshold: HarmBlockThreshold) {
        self.safety_settings = Some(vec![
            SafetySetting {
                category: HarmCategory::HarmCategoryHateSpeech,
                threshold: threshold.clone(),
            },
            SafetySetting {
                category: HarmCategory::HarmCategorySexuallyExplicit,
                threshold: threshold.clone(),
            },
            SafetySetting {
                category: HarmCategory::HarmCategoryDangerousContent,
                threshold: threshold.clone(),
            },
            SafetySetting {
                category: HarmCategory::HarmCategoryHarassment,
                threshold: threshold.clone(),
            },
        ]);
    }

    pub fn set_advance_settings(
        &mut self,
        stop_sequences: Option<Vec<String>>,
        response_mime_type: Option<String>,
        max_output_tokens: Option<u32>,
        temperature: Option<f32>,
        top_p: Option<f32>,
        top_k: Option<u32>,
        thinking_budget: Option<u32>,
    ) {
        self.generation_config = Some(GenerationConfig {
            stop_sequences,
            response_mime_type,
            max_output_tokens,
            temperature,
            top_p,
            top_k,
            thinking_config: match thinking_budget {
                Some(budget) => Some(ThinkingConfig::new(budget)),
                None => None,
            },
        });
    }

    pub fn set_temperature(&mut self, temperature: f32) {
        match &mut self.generation_config {
            Some(config) => config.temperature = Some(temperature),
            None => {
                self.generation_config = Some(GenerationConfig {
                    stop_sequences: None,
                    response_mime_type: None,
                    max_output_tokens: None,
                    temperature: Some(temperature),
                    top_p: None,
                    top_k: None,
                    thinking_config: None,
                });
            }
        }
    }

    pub fn set_max_output_tokens(&mut self, max_output_tokens: u32) {
        match &mut self.generation_config {
            Some(config) => config.max_output_tokens = Some(max_output_tokens),
            None => {
                self.generation_config = Some(GenerationConfig {
                    stop_sequences: None,
                    response_mime_type: None,
                    max_output_tokens: Some(max_output_tokens),
                    temperature: None,
                    top_p: None,
                    top_k: None,
                    thinking_config: None,
                });
            }
        }
    }

    /// Set the thinking budget for the generation config.
    /// By default, the thinking budget is None, which means the model will decide whether to think or not.
    /// Best to not use this, and let the model decide.
    pub fn set_thinking_budget(&mut self, thinking_budget: u32) {
        match &mut self.generation_config {
            Some(config) => config.thinking_config = Some(ThinkingConfig::new(thinking_budget)),
            None => {
                self.generation_config = Some(GenerationConfig {
                    stop_sequences: None,
                    response_mime_type: None,
                    max_output_tokens: None,
                    temperature: None,
                    top_p: None,
                    top_k: None,
                    thinking_config: Some(ThinkingConfig::new(thinking_budget)),
                });
            }
        }
    }

    pub fn set_system_instruction(&mut self, instruction: &str) {
        self.system_instruction = Some(instruction.to_string());
    }

    pub fn get_stream_max_json_size(&self) -> u32 {
        self.stream_max_json_size.unwrap_or(16384)
    }

    pub fn set_grounding_search(&mut self, enable: bool) {
        self.enable_grounding_search = enable;
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub(crate) struct GenerateContentRequest {
    contents: Vec<Content>, // Required: List of content objects (conversation history and latest request)
    safety_settings: Option<Vec<SafetySetting>>, // Optional: Safety settings to block unsafe content
    generation_config: Option<GenerationConfig>, // Optional: Configuration for model generation
    system_instruction: Option<NoRoleContent>,   // Optional: Developer set system instructions
    #[serde(skip_serializing_if = "Option::is_none")]
    tools: Option<Vec<Tool>>, // Optional: Grounding with Google Search
}

impl GenerateContentRequest {
    fn new(
        context: &Context,
        config: Option<GenerationConfig>,
        safety: Option<Vec<SafetySetting>>,
        system_instruction: Option<NoRoleContent>,
        tools: Option<Vec<Tool>>,
    ) -> Self {
        GenerateContentRequest {
            contents: context.contents.clone(),
            safety_settings: match safety {
                Some(s) => Some(s),
                None => Some(vec![
                    SafetySetting {
                        category: HarmCategory::HarmCategoryHateSpeech,
                        threshold: HarmBlockThreshold::BlockNone,
                    },
                    SafetySetting {
                        category: HarmCategory::HarmCategorySexuallyExplicit,
                        threshold: HarmBlockThreshold::BlockNone,
                    },
                    SafetySetting {
                        category: HarmCategory::HarmCategoryDangerousContent,
                        threshold: HarmBlockThreshold::BlockNone,
                    },
                    SafetySetting {
                        category: HarmCategory::HarmCategoryHarassment,
                        threshold: HarmBlockThreshold::BlockNone,
                    },
                ]),
            },
            generation_config: match config {
                Some(c) => Some(c),
                None => Some(GenerationConfig {
                    max_output_tokens: Some(8192),
                    temperature: Some(1.0),
                    response_mime_type: None,
                    stop_sequences: None,
                    top_k: None,
                    top_p: None,
                    thinking_config: None,
                }),
            },
            system_instruction,
            tools,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Context {
    contents: Vec<Content>,
}

impl Context {
    pub fn new() -> Self {
        Context {
            contents: Vec::new(),
        }
    }

    pub fn push_message(&mut self, role: Role, content: String) {
        self.contents.push(Content {
            role: Some(role),
            parts: vec![Part {
                data: PartData::Text {
                    text: content.to_string(),
                },
            }],
        });
    }

    pub fn push_file(&mut self, role: Role, file_data: FileData) {
        self.contents.push(Content {
            role: Some(role),
            parts: vec![Part {
                data: PartData::FileData { file_data },
            }],
        });
    }

    pub fn push_blob(&mut self, role: Role, blob: Blob) {
        self.contents.push(Content {
            role: Some(role),
            parts: vec![Part {
                data: PartData::InlineData { inline_data: blob },
            }],
        });
    }

    pub fn push_message_with_file(&mut self, role: Role, content: &str, file_data: FileData) {
        self.contents.push(Content {
            role: Some(role),
            parts: vec![
                Part {
                    data: PartData::Text {
                        text: content.to_string(),
                    },
                },
                Part {
                    data: PartData::FileData { file_data },
                },
            ],
        });
    }

    pub fn push_message_with_blob(&mut self, role: Role, content: &str, blob: Blob) {
        self.contents.push(Content {
            role: Some(role),
            parts: vec![
                Part {
                    data: PartData::Text {
                        text: content.to_string(),
                    },
                },
                Part {
                    data: PartData::InlineData { inline_data: blob },
                },
            ],
        });
    }

    pub fn build(&self, settings: &Settings) -> GenerateContentRequest {
        let tools = if settings.enable_grounding_search {
            Some(vec![Tool {
                google_search_retrieval: GoogleSearchRetrieval {},
            }])
        } else {
            None
        };

        GenerateContentRequest {
            contents: self.contents.clone(),
            safety_settings: settings.safety_settings.clone(),
            generation_config: settings.generation_config.clone(),
            system_instruction: match &settings.system_instruction {
                Some(instruction) => Some(NoRoleContent {
                    parts: vec![Part {
                        data: PartData::Text {
                            text: instruction.clone(),
                        },
                    }],
                }),
                None => None,
            },
            tools,
        }
    }

    pub fn clear(&mut self) {
        self.contents.clear();
    }

    pub fn is_empty(&self) -> bool {
        self.contents.is_empty()
    }

    pub fn len(&self) -> usize {
        self.contents.len()
    }

    pub fn get_contents(&self) -> &Vec<Content> {
        &self.contents
    }

    pub fn get_contents_mut(&mut self) -> &mut Vec<Content> {
        &mut self.contents
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum BatchState {
    JobStateUnspecified,
    JobStateQueued,
    JobStateRunning,
    JobStateCancelling,
    JobStateSucceeded,
    JobStateFailed,
    JobStateCancelled,
    #[serde(other)]
    Unknown,
}

impl BatchState {
    pub fn is_terminal(&self) -> bool {
        matches!(
            self,
            Self::JobStateSucceeded | Self::JobStateFailed | Self::JobStateCancelled
        )
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct BatchStats {
    pub request_count: Option<u64>,
    pub completed_request_count: Option<u64>,
    pub failed_request_count: Option<u64>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct BatchOutputFile {
    #[serde(default, alias = "fileName", alias = "name")]
    pub file_name: String,
    #[serde(default, alias = "fileUri", alias = "uri")]
    pub file_uri: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct GenerateContentBatchOutput {
    #[serde(default, alias = "responsesFile")]
    pub responses_file: Option<BatchOutputFile>,
    #[serde(default, alias = "failedRequestsFile")]
    pub failed_requests_file: Option<BatchOutputFile>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct Batch {
    pub name: Option<String>,
    pub display_name: Option<String>,
    pub model: Option<String>,
    pub state: Option<BatchState>,
    pub create_time: Option<String>,
    pub update_time: Option<String>,
    pub end_time: Option<String>,
    pub error: Option<Error>,
    pub stats: Option<BatchStats>,
    pub output: Option<GenerateContentBatchOutput>,
    #[serde(alias = "response")]
    pub response_output: Option<GenerateContentBatchOutput>,
}

impl Batch {
    pub fn output(&self) -> Option<&GenerateContentBatchOutput> {
        self.output.as_ref().or(self.response_output.as_ref())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct OperationStatus {
    pub code: i32,
    pub message: String,
    pub details: Option<Vec<Value>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct BatchOperation {
    pub name: String,
    #[serde(default)]
    pub done: bool,
    pub metadata: Option<Value>,
    pub response: Option<Value>,
    pub error: Option<OperationStatus>,
}

impl BatchOperation {
    pub fn batch(&self) -> Option<Batch> {
        fn parse_batch(value: &Value) -> Option<Batch> {
            if let Ok(batch) = serde_json::from_value::<Batch>(value.clone()) {
                return Some(batch);
            }

            value
                .get("batch")
                .and_then(|inner| serde_json::from_value::<Batch>(inner.clone()).ok())
        }

        self.response
            .as_ref()
            .and_then(parse_batch)
            .or_else(|| self.metadata.as_ref().and_then(parse_batch))
    }

    pub fn batch_state(&self) -> Option<BatchState> {
        self.batch().and_then(|batch| batch.state)
    }

    pub fn is_terminal(&self) -> bool {
        if self.done {
            return true;
        }

        self.batch_state().is_some_and(|state| state.is_terminal())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct ListOperationsResponse {
    #[serde(default)]
    pub operations: Vec<BatchOperation>,
    pub next_page_token: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BatchCreateInputConfig {
    pub file_name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BatchCreateOutputConfig {
    pub file_name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BatchCreateBody {
    pub file_name: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BatchCreatePayload {
    pub input_config: BatchCreateInputConfig,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_config: Option<BatchCreateOutputConfig>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub src: Option<BatchCreateBody>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dest: Option<BatchCreateBody>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BatchCreateRequest {
    pub batch: BatchCreatePayload,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub struct BatchJsonlLine {
    pub key: String,
    pub response: Option<GenerateContentResponse>,
    pub error: Option<Error>,
}

pub fn parse_batch_jsonl_lines(content: &str) -> Result<Vec<BatchJsonlLine>, GemError> {
    let mut lines = Vec::new();
    for line in content.lines() {
        if line.trim().is_empty() {
            continue;
        }
        let parsed = serde_json::from_str::<BatchJsonlLine>(line)
            .map_err(|err| GemError::FileError(format!("Failed to parse JSONL line: {}", err)))?;
        lines.push(parsed);
    }
    Ok(lines)
}

pub fn group_batch_jsonl_by_key(
    lines: Vec<BatchJsonlLine>,
) -> BTreeMap<String, Vec<BatchJsonlLine>> {
    let mut grouped = BTreeMap::new();
    for line in lines {
        grouped
            .entry(line.key.clone())
            .or_insert_with(Vec::new)
            .push(line);
    }
    grouped
}

#[cfg(test)]
mod tests {
    use super::{
        group_batch_jsonl_by_key, parse_batch_jsonl_lines, BatchCreateInputConfig,
        BatchCreatePayload, BatchCreateRequest, BatchOperation,
    };

    #[test]
    fn parse_batch_jsonl_ok() {
        let data = r#"{"key":"0","response":{"candidates":[{"content":{"parts":[{"text":"hello"}]}}]}}
{"key":"1","error":{"code":400,"message":"bad request","status":"INVALID_ARGUMENT"}}"#;
        let lines = parse_batch_jsonl_lines(data).expect("jsonl should parse");
        assert_eq!(lines.len(), 2);
        let grouped = group_batch_jsonl_by_key(lines);
        assert!(grouped.contains_key("0"));
        assert!(grouped.contains_key("1"));
    }

    #[test]
    fn batch_operation_terminal_from_state() {
        let op_json = r#"{
            "name":"operations/123",
            "done":false,
            "metadata":{"batch":{"state":"JOB_STATE_SUCCEEDED"}}
        }"#;
        let operation: BatchOperation = serde_json::from_str(op_json).expect("operation parse");
        assert!(operation.is_terminal());
    }

    #[test]
    fn batch_create_request_serialization() {
        let payload = BatchCreateRequest {
            batch: BatchCreatePayload {
                input_config: BatchCreateInputConfig {
                    file_name: "files/input".to_string(),
                },
                output_config: None,
                src: None,
                dest: None,
                display_name: Some("test".to_string()),
            },
        };
        let json = serde_json::to_value(payload).expect("serialize");
        assert!(json.get("batch").is_some());
        assert!(json["batch"]
            .get("inputConfig")
            .and_then(|v| v.get("fileName"))
            .is_some());
        assert!(json["batch"].get("outputConfig").is_none());
        assert!(json["batch"].get("src").is_none());
        assert!(json["batch"].get("dest").is_none());
    }
}
