services:
  redis:
    image: redis:latest
    container_name: fulturate_redis
    restart: unless-stopped
    networks:
      - fulturate-net
    volumes:
      - redis-data:/data/redis

  mongo:
    image: mongo:latest
    container_name: fulturate_mongo
    restart: unless-stopped
    networks:
      - fulturate-net
    volumes:
      - mongo-data:/data/db

  telegram_api:
    image: aiogram/telegram-bot-api:latest
    container_name: fulturate_telegram_api
    restart: unless-stopped
    networks:
      - fulturate-net
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - TELEGRAM_LOCAL=1
      - TELEGRAM_API_ID=28090001
      - TELEGRAM_API_HASH=a38cfe08329526d8cb130acbdddacbbd
    volumes:
      - ./data/telegram-bot-api:/var/lib/telegram-bot-api

  fulturate:
    build:
      context: .
      target: dev-env
    container_name: fulturate_bot
    restart: unless-stopped
    depends_on:
      - redis
      - mongo
      - telegram_api
    networks:
      - fulturate-net
    env_file:
      - .env
    environment:
      - CARGO_TARGET_DIR=/app/target
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    command: cargo run --bin fulturate

volumes:
  cargo-cache:
  target-cache:
  mongo-data:
  redis-data:


networks:
  fulturate-net:
    driver: bridge
