services:
  redis:
    image: redis:latest
    container_name: fulturate_redis
    restart: unless-stopped
    networks:
      - fulturate-net
    volumes:
      - redis_data:/data

  mongo:
    image: mongo:latest
    container_name: fulturate_mongo
    restart: unless-stopped
    networks:
      - fulturate-net
    volumes:
      - mongo_data:/data/db

  telegram_api:
    image: aiogram/telegram-bot-api:latest
    container_name: fulturate_telegram_api
    restart: unless-stopped
    networks:
      - fulturate-net
#    ports:
#      - "8081:8081"
    env_file:
      - .env
    environment:
      - TELEGRAM_LOCAL=1
      - TELEGRAM_API_ID=28090001
      - TELEGRAM_API_HASH=a38cfe08329526d8cb130acbdddacbbd
    volumes:
      - telegram_bot_api_data:/var/lib/telegram-bot-api

  fulturate:
    build:
      context: .
      target: dev-env
    container_name: fulturate_bot
    restart: unless-stopped
    depends_on:
      - redis
      - mongo
      - telegram_api
    networks:
      - fulturate-net
    env_file:
      - .env
    environment:
      - CARGO_TARGET_DIR=/app/target
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
      - telegram_bot_api_data:/var/lib/telegram-bot-api
    command: >
      sh -c '
      if [ "$RELEASE" = "1" ]; then
        echo "Release"
        exec cargo run --release --bin fulturate
      else
        echo "Debug"
        exec cargo run --bin fulturate
        fi
      '

volumes:
  cargo-cache:
  target-cache:
  mongo_data:
  redis_data:
  telegram_bot_api_data:
    driver: local


networks:
  fulturate-net:
    driver: bridge
